const mongoose = require('mongoose');

/**
 * Alert Schema
 * Stores alerts generated by users (panic, SOS, danger zone entry)
 */
const alertSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User ID is required'],
      index: true,
    },
    location: {
      lat: {
        type: Number,
        required: [true, 'Latitude is required'],
      },
      lng: {
        type: Number,
        required: [true, 'Longitude is required'],
      },
    },
    alertType: {
      type: String,
      required: [true, 'Alert type is required'],
      enum: ['panic', 'sos', 'danger_zone_entry'],
      index: true,
    },
    timestamp: {
      type: Date,
      default: Date.now,
      index: true,
    },
    status: {
      type: String,
      enum: ['pending', 'viewed', 'resolved'],
      default: 'pending',
      index: true,
    },
    message: {
      type: String,
      default: '',
    },
  },
  {
    timestamps: true,
  }
);

// Index for efficient queries
alertSchema.index({ status: 1, timestamp: -1 });
alertSchema.index({ userId: 1, timestamp: -1 });

module.exports = mongoose.model('Alert', alertSchema);



