import 'package:flutter/foundation.dart';
import 'package:intl/intl.dart';
import 'package:hive/hive.dart';

class LocalizationService {
  static const String boxName = 'localizationBox';
  static const String languageKey = 'selectedLanguage';
  static final ValueNotifier<String> _languageNotifier =
      ValueNotifier<String>('en');
  
  static const Map<String, Map<String, String>> translations = {
    'en': {
      // Dashboard
      'dashboard': 'Dashboard',
      'safety_score': 'Safety Score',
      'current_location': 'Current Location',
      'nearby_zones': 'Nearby Zones',
      'active_alerts': 'Active Alerts',
      
      // Profile
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'name': 'Name',
      'email': 'Email',
      'phone': 'Phone',
      'country': 'Country',
      'emergency_contacts': 'Emergency Contacts',
      'member_since': 'Member Since',
      
      // Explore
      'explore': 'Explore',
      'nearby_places': 'Nearby Places',
      'categories': 'Categories',
      'all': 'All',
      'famous': 'Famous',
      'food': 'Food',
      'adventure': 'Adventure',
      'hidden_gems': 'Hidden Gems',
      
      // Emergency
      'emergency': 'Emergency',
      'sos': 'SOS',
      'press_and_hold': 'Press and Hold',
      'police': 'Police',
      'ambulance': 'Ambulance',
      'fire': 'Fire Department',
      'share_location': 'Share My Location',
      'call_police': 'Call Police',
      'report_incident': 'Report Incident',
      
      // Incident Report
      'incident_report': 'Report Incident',
      'incident_title': 'Incident Title',
      'category': 'Category',
      'urgency_level': 'Urgency Level',
      'description': 'Description',
      'location': 'Location',
      'submit_report': 'Submit Report',
      'incident_reported': 'Incident Reported',
      'low': 'Low',
      'medium': 'Medium',
      'high': 'High',
      'critical': 'Critical',
      
      // Settings
      'settings': 'Settings',
      'language': 'Language',
      'notifications': 'Notifications',
      'enable_notifications': 'Enable Notifications',
      'dark_mode': 'Dark Mode',
      'location_tracking': 'Location Tracking',
      'enable_location_tracking': 'Enable Location Tracking',
      'about': 'About',
      'version': 'Version',
      'logout': 'Logout',
      
      // Common
      'ok': 'OK',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'close': 'Close',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'no_data': 'No data available',
      'place': 'Place',
      'distance': 'Distance',
      'view_details': 'View Details',
      'out_of_100': 'Out of 100',
      'current_zone': 'Current Zone',
      'time': 'Time',
      'crowd_density': 'Crowd Density',
      'weather': 'Weather',
      'detecting_address': 'Detecting address...',
      'no_active_alerts': 'No active alerts right now. Stay safe!',
      'alert': 'Alert',
      'info': 'Info',
      'details_unavailable': 'Details unavailable.',
      'weather_data_unavailable': 'Latest weather data unavailable.',
      'rain': 'Rain',
      'safe_status': 'Safe',
      'caution_status': 'Caution',
      'danger_status': 'Danger',
      'updating': 'Updating...',
      'unknown': 'Unknown',
      'calculating': 'Calculating...',
      'detecting': 'Detecting...',
      'moments_ago': 'moments ago',
      'just_now': 'just now',
      'minutes_ago_suffix': 'min ago',
      'hours_ago_suffix': 'hr ago',
      'days_ago_suffix': 'd ago',
      'entered_zone_title': 'Entered Zone',
      'entered_zone_message': 'You entered',
      'tourist_zone': 'Tourist Zone',
      'market_area': 'Market Area',
      'remote_forest': 'Remote Forest',
      'local_police_station': 'Local Police Station',
      'sos_alert': 'SOS Alert',
      'sos_dialog_message': 'Are you in danger? This will alert emergency services.',
      'send_sos': 'Send SOS',
      'sos_sent': 'SOS alert sent!',
      'brief_title_hint': 'Brief title of the incident',
      'enter_incident_title': 'Please enter incident title',
      'select_category': 'Please select a category',
      'select_urgency': 'Please select urgency level',
      'description_hint': 'Provide detailed description of the incident',
      'enter_description': 'Please enter description',
      'description_min': 'Description must be at least 10 characters',
      'update_location': 'Update Location',
      'getting_location': 'Getting location...',
      'error_getting_location': 'Error getting current location',
      'incident_id_label': 'Incident ID',
      'incident_report_success': 'Your incident has been reported and authorities have been notified.',
      'report_info': '📢 Your report will be immediately sent to local authorities. They may contact you for additional information. Keep your incident ID for reference.',
      'theft': 'Theft',
      'assault': 'Assault',
      'medical_emergency': 'Medical Emergency',
      'accident': 'Accident',
      'missing_person': 'Missing Person',
      'suspicious_activity': 'Suspicious Activity',
      'other': 'Other',
    },
    'hi': {
      // Dashboard
      'dashboard': 'डैशबोर्ड',
      'safety_score': 'सुरक्षा स्कोर',
      'current_location': 'वर्तमान स्थान',
      'nearby_zones': 'निकटवर्ती क्षेत्र',
      'active_alerts': 'सक्रिय अलर्ट',
      
      // Profile
      'profile': 'प्रोफाइल',
      'edit_profile': 'प्रोफाइल संपादित करें',
      'name': 'नाम',
      'email': 'ईमेल',
      'phone': 'फोन',
      'country': 'देश',
      'emergency_contacts': 'आपातकालीन संपर्क',
      'member_since': 'सदस्य बनने की तारीख',
      
      // Explore
      'explore': 'अन्वेषण करें',
      'nearby_places': 'निकटवर्ती स्थान',
      'categories': 'श्रेणियां',
      'all': 'सभी',
      'famous': 'प्रसिद्ध',
      'food': 'भोजन',
      'adventure': 'रोमांच',
      'hidden_gems': 'छिपे हुए रत्न',
      
      // Emergency
      'emergency': 'आपातकाल',
      'sos': 'एसओएस',
      'press_and_hold': 'दबाएं और होल्ड करें',
      'police': 'पुलिस',
      'ambulance': 'एम्बुलेंस',
      'fire': 'अग्निशमन विभाग',
      'share_location': 'अपना स्थान साझा करें',
      'call_police': 'पुलिस को कॉल करें',
      'report_incident': 'घटना की रिपोर्ट करें',
      
      // Incident Report
      'incident_report': 'घटना की रिपोर्ट करें',
      'incident_title': 'घटना का शीर्षक',
      'category': 'श्रेणी',
      'urgency_level': 'आपातकाल का स्तर',
      'description': 'विवरण',
      'location': 'स्थान',
      'submit_report': 'रिपोर्ट जमा करें',
      'incident_reported': 'घटना की सूचना दी गई',
      'low': 'कम',
      'medium': 'मध्यम',
      'high': 'अधिक',
      'critical': 'गंभीर',
      
      // Settings
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'notifications': 'सूचनाएं',
      'enable_notifications': 'सूचनाओं को सक्षम करें',
      'dark_mode': 'डार्क मोड',
      'location_tracking': 'स्थान ट्रैकिंग',
      'enable_location_tracking': 'स्थान ट्रैकिंग को सक्षम करें',
      'about': 'के बारे में',
      'version': 'संस्करण',
      'logout': 'लॉग आउट',
      
      // Common
      'ok': 'ठीक है',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'delete': 'हटाएं',
      'edit': 'संपादित करें',
      'add': 'जोड़ें',
      'close': 'बंद करें',
      'loading': 'लोड हो रहा है...',
      'error': 'त्रुटि',
      'success': 'सफलता',
      'no_data': 'कोई डेटा उपलब्ध नहीं',
      'place': 'स्थान',
      'distance': 'दूरी',
      'view_details': 'विवरण देखें',
      'out_of_100': '100 में से',
      'current_zone': 'वर्तमान क्षेत्र',
      'time': 'समय',
      'crowd_density': 'भीड़ घनत्व',
      'weather': 'मौसम',
      'detecting_address': 'पता खोजा जा रहा है...',
      'no_active_alerts': 'अभी कोई सक्रिय अलर्ट नहीं। सुरक्षित रहें!',
      'alert': 'अलर्ट',
      'info': 'जानकारी',
      'details_unavailable': 'विवरण उपलब्ध नहीं।',
      'weather_data_unavailable': 'नवीनतम मौसम डेटा उपलब्ध नहीं।',
      'rain': 'बारिश',
      'safe_status': 'सुरक्षित',
      'caution_status': 'सावधानी',
      'danger_status': 'खतरा',
      'updating': 'अपडेट किया जा रहा है...',
      'unknown': 'अज्ञात',
      'calculating': 'गणना हो रही है...',
      'detecting': 'डिटेक्ट किया जा रहा है...',
      'moments_ago': 'कुछ क्षण पहले',
      'just_now': 'अभी अभी',
      'minutes_ago_suffix': 'मिन पहले',
      'hours_ago_suffix': 'घंटे पहले',
      'days_ago_suffix': 'दिन पहले',
      'entered_zone_title': 'क्षेत्र में प्रवेश किया',
      'entered_zone_message': 'आप प्रवेश कर चुके हैं',
      'tourist_zone': 'पर्यटक क्षेत्र',
      'market_area': 'बाजार क्षेत्र',
      'remote_forest': 'दूरस्थ वन',
      'local_police_station': 'स्थानीय थाना',
      'sos_alert': 'एसओएस अलर्ट',
      'sos_dialog_message': 'क्या आप खतरे में हैं? इससे आपातकालीन सेवाओं को सूचना मिलेगी।',
      'send_sos': 'एसओएस भेजें',
      'sos_sent': 'एसओएस अलर्ट भेजा गया!',
      'brief_title_hint': 'घटना का संक्षिप्त शीर्षक',
      'enter_incident_title': 'कृपया घटना का शीर्षक दर्ज करें',
      'select_category': 'कृपया श्रेणी चुनें',
      'select_urgency': 'कृपया आपातकाल स्तर चुनें',
      'description_hint': 'घटना का विस्तृत विवरण प्रदान करें',
      'enter_description': 'कृपया विवरण दर्ज करें',
      'description_min': 'विवरण कम से कम 10 अक्षरों का होना चाहिए',
      'update_location': 'स्थान अपडेट करें',
      'getting_location': 'स्थान प्राप्त किया जा रहा है...',
      'error_getting_location': 'वर्तमान स्थान प्राप्त करने में त्रुटि',
      'incident_id_label': 'घटना आईडी',
      'incident_report_success': 'आपकी घटना दर्ज कर ली गई है और अधिकारियों को सूचित कर दिया गया है।',
      'report_info': '📢 आपकी रिपोर्ट तुरंत स्थानीय अधिकारियों को भेज दी जाएगी। वे अतिरिक्त जानकारी के लिए आपसे संपर्क कर सकते हैं। संदर्भ के लिए अपनी घटना आईडी संभालकर रखें।',
      'theft': 'चोरी',
      'assault': 'हमला',
      'medical_emergency': 'चिकित्सीय आपातकाल',
      'accident': 'दुर्घटना',
      'missing_person': 'लापता व्यक्ति',
      'suspicious_activity': 'संदिग्ध गतिविधि',
      'other': 'अन्य',
    },
    'es': {
      // Dashboard
      'dashboard': 'Panel de control',
      'safety_score': 'Puntuación de seguridad',
      'current_location': 'Ubicación actual',
      'nearby_zones': 'Zonas cercanas',
      'active_alerts': 'Alertas activas',
      
      // Profile
      'profile': 'Perfil',
      'edit_profile': 'Editar perfil',
      'name': 'Nombre',
      'email': 'Correo electrónico',
      'phone': 'Teléfono',
      'country': 'País',
      'emergency_contacts': 'Contactos de emergencia',
      'member_since': 'Miembro desde',
      
      // Explore
      'explore': 'Explorar',
      'nearby_places': 'Lugares cercanos',
      'categories': 'Categorías',
      'all': 'Todos',
      'famous': 'Famoso',
      'food': 'Comida',
      'adventure': 'Aventura',
      'hidden_gems': 'Joyas ocultas',
      
      // Emergency
      'emergency': 'Emergencia',
      'sos': 'SOS',
      'press_and_hold': 'Presione y mantenga',
      'police': 'Policía',
      'ambulance': 'Ambulancia',
      'fire': 'Bomberos',
      'share_location': 'Compartir mi ubicación',
      'call_police': 'Llamar a la policía',
      'report_incident': 'Reportar incidente',
      
      // Incident Report
      'incident_report': 'Reportar incidente',
      'incident_title': 'Título del incidente',
      'category': 'Categoría',
      'urgency_level': 'Nivel de urgencia',
      'description': 'Descripción',
      'location': 'Ubicación',
      'submit_report': 'Enviar reporte',
      'incident_reported': 'Incidente reportado',
      'low': 'Bajo',
      'medium': 'Medio',
      'high': 'Alto',
      'critical': 'Crítico',
      
      // Settings
      'settings': 'Configuración',
      'language': 'Idioma',
      'notifications': 'Notificaciones',
      'enable_notifications': 'Habilitar notificaciones',
      'dark_mode': 'Modo oscuro',
      'location_tracking': 'Seguimiento de ubicación',
      'enable_location_tracking': 'Habilitar seguimiento de ubicación',
      'about': 'Acerca de',
      'version': 'Versión',
      'logout': 'Cerrar sesión',
      
      // Common
      'ok': 'OK',
      'cancel': 'Cancelar',
      'save': 'Guardar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'add': 'Añadir',
      'close': 'Cerrar',
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      'no_data': 'No hay datos disponibles',
      'place': 'Lugar',
      'distance': 'Distancia',
      'view_details': 'Ver detalles',
      'out_of_100': 'De 100',
      'current_zone': 'Zona actual',
      'time': 'Hora',
      'crowd_density': 'Densidad de gente',
      'weather': 'Clima',
      'detecting_address': 'Detectando dirección...',
      'no_active_alerts': 'No hay alertas activas ahora. ¡Mantente seguro!',
      'alert': 'Alerta',
      'info': 'Info',
      'details_unavailable': 'Detalles no disponibles.',
      'weather_data_unavailable': 'Datos meteorológicos no disponibles.',
      'rain': 'Lluvia',
      'safe_status': 'Seguro',
      'caution_status': 'Precaución',
      'danger_status': 'Peligro',
      'updating': 'Actualizando...',
      'unknown': 'Desconocido',
      'calculating': 'Calculando...',
      'detecting': 'Detectando...',
      'moments_ago': 'hace unos momentos',
      'just_now': 'justo ahora',
      'minutes_ago_suffix': 'min atrás',
      'hours_ago_suffix': 'h atrás',
      'days_ago_suffix': 'días atrás',
      'entered_zone_title': 'Zona ingresada',
      'entered_zone_message': 'Ingresaste a',
      'tourist_zone': 'Zona turística',
      'market_area': 'Área de mercado',
      'remote_forest': 'Bosque remoto',
      'local_police_station': 'Comisaría local',
      'sos_alert': 'Alerta SOS',
      'sos_dialog_message': '¿Estás en peligro? Esto alertará a los servicios de emergencia.',
      'send_sos': 'Enviar SOS',
      'sos_sent': '¡Alerta SOS enviada!',
      'brief_title_hint': 'Título breve del incidente',
      'enter_incident_title': 'Por favor ingresa el título del incidente',
      'select_category': 'Por favor selecciona una categoría',
      'select_urgency': 'Por favor selecciona el nivel de urgencia',
      'description_hint': 'Proporciona una descripción detallada del incidente',
      'enter_description': 'Por favor ingresa una descripción',
      'description_min': 'La descripción debe tener al menos 10 caracteres',
      'update_location': 'Actualizar ubicación',
      'getting_location': 'Obteniendo ubicación...',
      'error_getting_location': 'Error al obtener la ubicación actual',
      'incident_id_label': 'ID del incidente',
      'incident_report_success': 'Tu incidente ha sido reportado y las autoridades han sido notificadas.',
      'report_info': '📢 Tu reporte se enviará inmediatamente a las autoridades locales. Ellos pueden contactarte para más información. Conserva tu ID de incidente como referencia.',
      'theft': 'Robo',
      'assault': 'Agresión',
      'medical_emergency': 'Emergencia médica',
      'accident': 'Accidente',
      'missing_person': 'Persona desaparecida',
      'suspicious_activity': 'Actividad sospechosa',
      'other': 'Otro',
    },
    'bn': {
      // Dashboard
      'dashboard': 'ড্যাশবোর্ড',
      'safety_score': 'নিরাপত্তা স্কোর',
      'current_location': 'বর্তমান অবস্থান',
      'nearby_zones': 'নিকটবর্তী অঞ্চল',
      'active_alerts': 'সক্রিয় সতর্কতা',
      
      // Profile
      'profile': 'প্রোফাইল',
      'edit_profile': 'প্রোফাইল সম্পাদনা করুন',
      'name': 'নাম',
      'email': 'ইমেইল',
      'phone': 'ফোন',
      'country': 'দেশ',
      'emergency_contacts': 'জরুরি পরিচিতি',
      'member_since': 'সদস্য হওয়ার পর থেকে',
      
      // Explore
      'explore': 'অন্বেষণ',
      'nearby_places': 'নিকটবর্তী স্থান',
      'categories': 'বিভাগসমূহ',
      'all': 'সব',
      'famous': 'বিখ্যাত',
      'food': 'খাবার',
      'adventure': 'রোমাঞ্চ',
      'hidden_gems': 'লুকানো রত্ন',
      
      // Emergency
      'emergency': 'জরুরি',
      'sos': 'এসওএস',
      'press_and_hold': 'চাপুন এবং ধরে রাখুন',
      'police': 'পুলিশ',
      'ambulance': 'অ্যাম্বুলেন্স',
      'fire': 'দমকল বিভাগ',
      'share_location': 'আমার অবস্থান শেয়ার করুন',
      'call_police': 'পুলিশকে কল করুন',
      'report_incident': 'ঘটনা রিপোর্ট করুন',
      
      // Incident Report
      'incident_report': 'ঘটনা রিপোর্ট',
      'incident_title': 'ঘটনার শিরোনাম',
      'category': 'বিভাগ',
      'urgency_level': 'জরুরিতা স্তর',
      'description': 'বিবরণ',
      'location': 'অবস্থান',
      'submit_report': 'রিপোর্ট জমা দিন',
      'incident_reported': 'ঘটনা রিপোর্ট হয়েছে',
      'low': 'নিম্ন',
      'medium': 'মাঝারি',
      'high': 'উচ্চ',
      'critical': 'সংকটজনক',
      
      // Settings
      'settings': 'সেটিংস',
      'language': 'ভাষা',
      'notifications': 'বিজ্ঞপ্তি',
      'enable_notifications': 'বিজ্ঞপ্তি সক্রিয় করুন',
      'dark_mode': 'ডার্ক মোড',
      'location_tracking': 'অবস্থান ট্র্যাকিং',
      'enable_location_tracking': 'অবস্থান ট্র্যাকিং সক্রিয় করুন',
      'about': 'সম্পর্কে',
      'version': 'সংস্করণ',
      'logout': 'লগ আউট',
      
      // Common
      'ok': 'ঠিক আছে',
      'cancel': 'বাতিল',
      'save': 'সংরক্ষণ করুন',
      'delete': 'মুছে ফেলুন',
      'edit': 'সম্পাদনা',
      'add': 'যোগ করুন',
      'close': 'বন্ধ করুন',
      'loading': 'লোড হচ্ছে...',
      'error': 'ত্রুটি',
      'success': 'সফলতা',
      'no_data': 'কোনো তথ্য নেই',
      'place': 'স্থান',
      'distance': 'দূরত্ব',
      'view_details': 'বিস্তারিত দেখুন',
      'out_of_100': '১০০ এর মধ্যে',
      'current_zone': 'বর্তমান অঞ্চল',
      'time': 'সময়',
      'crowd_density': 'ভিড়ের ঘনত্ব',
      'weather': 'আবহাওয়া',
      'detecting_address': 'ঠিকানা অনুসন্ধান করা হচ্ছে...',
      'no_active_alerts': 'কোনো সক্রিয় সতর্কতা নেই। নিরাপদ থাকুন!',
      'alert': 'সতর্কতা',
      'info': 'তথ্য',
      'details_unavailable': 'বিস্তারিত উপলব্ধ নয়।',
      'weather_data_unavailable': 'সর্বশেষ আবহাওয়ার তথ্য নেই।',
      'rain': 'বৃষ্টি',
      'safe_status': 'নিরাপদ',
      'caution_status': 'সতর্কতা',
      'danger_status': 'বিপদ',
      'updating': 'আপডেট করা হচ্ছে...',
      'unknown': 'অজানা',
      'calculating': 'গণনা চলছে...',
      'detecting': 'সনাক্ত করা হচ্ছে...',
      'moments_ago': 'কিছুক্ষণ আগে',
      'just_now': 'এইমাত্র',
      'minutes_ago_suffix': 'মিনিট আগে',
      'hours_ago_suffix': 'ঘণ্টা আগে',
      'days_ago_suffix': 'দিন আগে',
      'entered_zone_title': 'অঞ্চলে প্রবেশ',
      'entered_zone_message': 'আপনি প্রবেশ করেছেন',
      'tourist_zone': 'পর্যটন অঞ্চল',
      'market_area': 'বাজার এলাকা',
      'remote_forest': 'দূরবর্তী বন',
      'local_police_station': 'স্থানীয় থানায়',
      'sos_alert': 'এসওএস সতর্কতা',
      'sos_dialog_message': 'আপনি কি বিপদে আছেন? এটি জরুরি পরিষেবাকে সতর্ক করবে।',
      'send_sos': 'এসওএস পাঠান',
      'sos_sent': 'এসওএস সতর্কতা পাঠানো হয়েছে!',
      'brief_title_hint': 'ঘটনার সংক্ষিপ্ত শিরোনাম',
      'enter_incident_title': 'দয়া করে ঘটনার শিরোনাম লিখুন',
      'select_category': 'অনুগ্রহ করে একটি বিভাগ নির্বাচন করুন',
      'select_urgency': 'অনুগ্রহ করে জরুরিতা স্তর নির্বাচন করুন',
      'description_hint': 'ঘটনার বিস্তারিত বিবরণ দিন',
      'enter_description': 'অনুগ্রহ করে বিবরণ লিখুন',
      'description_min': 'বিবরণে অন্তত ১০ অক্ষর থাকতে হবে',
      'update_location': 'অবস্থান আপডেট করুন',
      'getting_location': 'অবস্থান পাওয়া যাচ্ছে...',
      'error_getting_location': 'বর্তমান অবস্থান আনতে ত্রুটি',
      'incident_id_label': 'ঘটনা আইডি',
      'incident_report_success': 'আপনার ঘটনা রিপোর্ট করা হয়েছে এবং কর্তৃপক্ষকে জানানো হয়েছে।',
      'report_info': '📢 আপনার রিপোর্ট সঙ্গে সঙ্গেই স্থানীয় কর্তৃপক্ষের কাছে পাঠানো হবে। অতিরিক্ত তথ্যের জন্য তারা আপনার সঙ্গে যোগাযোগ করতে পারে। রেফারেন্সের জন্য আপনার ঘটনা আইডি সংরক্ষণ করুন।',
      'theft': 'চুরি',
      'assault': 'আক্রমণ',
      'medical_emergency': 'চিকিৎসা জরুরি অবস্থা',
      'accident': 'দুর্ঘটনা',
      'missing_person': 'নিখোঁজ ব্যক্তি',
      'suspicious_activity': 'সন্দেহজনক কার্যকলাপ',
      'other': 'অন্যান্য',
    },
    'mr': {
      // Dashboard
      'dashboard': 'डॅशबोर्ड',
      'safety_score': 'सुरक्षितता गुण',
      'current_location': 'वर्तमान स्थान',
      'nearby_zones': 'जवळची क्षेत्रे',
      'active_alerts': 'सक्रिय सूचना',
      
      // Profile
      'profile': 'प्रोफाइल',
      'edit_profile': 'प्रोफाइल संपादित करा',
      'name': 'नाव',
      'email': 'ईमेल',
      'phone': 'फोन',
      'country': 'देश',
      'emergency_contacts': 'आपत्कालीन संपर्क',
      'member_since': 'सदस्य झाल्यापासून',
      
      // Explore
      'explore': 'अन्वेषण',
      'nearby_places': 'जवळची ठिकाणे',
      'categories': 'श्रेणी',
      'all': 'सर्व',
      'famous': 'प्रसिद्ध',
      'food': 'अन्न',
      'adventure': 'रोमांच',
      'hidden_gems': 'लपलेली रत्ने',
      
      // Emergency
      'emergency': 'आपत्काल',
      'sos': 'एसओएस',
      'press_and_hold': 'दाबा आणि धरून ठेवा',
      'police': 'पोलीस',
      'ambulance': 'रुग्णवाहिका',
      'fire': 'अग्निशमन विभाग',
      'share_location': 'माझे स्थान शेअर करा',
      'call_police': 'पोलीसांना कॉल करा',
      'report_incident': 'घटना नोंदवा',
      
      // Incident Report
      'incident_report': 'घटना अहवाल',
      'incident_title': 'घटनेचे शीर्षक',
      'category': 'श्रेणी',
      'urgency_level': 'आपत्कालीन स्तर',
      'description': 'वर्णन',
      'location': 'स्थान',
      'submit_report': 'अहवाल सबमिट करा',
      'incident_reported': 'घटना नोंदली गेली',
      'low': 'कमी',
      'medium': 'मध्यम',
      'high': 'जास्त',
      'critical': 'गंभीर',
      
      // Settings
      'settings': 'सेटिंग्ज',
      'language': 'भाषा',
      'notifications': 'सूचना',
      'enable_notifications': 'सूचना सक्षम करा',
      'dark_mode': 'डार्क मोड',
      'location_tracking': 'स्थान ट्रॅकिंग',
      'enable_location_tracking': 'स्थान ट्रॅकिंग सक्षम करा',
      'about': 'बद्दल',
      'version': 'आवृत्ती',
      'logout': 'लॉग आऊट',
      
      // Common
      'ok': 'ठीक आहे',
      'cancel': 'रद्द करा',
      'save': 'जतन करा',
      'delete': 'हटवा',
      'edit': 'संपादित करा',
      'add': 'जोडा',
      'close': 'बंद करा',
      'loading': 'लोड होत आहे...',
      'error': 'त्रुटी',
      'success': 'यश',
      'no_data': 'डेटा उपलब्ध नाही',
      'place': 'ठिकाण',
      'distance': 'अंतर',
      'view_details': 'तपशील पाहा',
      'out_of_100': '100 पैकी',
      'current_zone': 'सध्याचे क्षेत्र',
      'time': 'वेळ',
      'crowd_density': 'गर्दीची घनता',
      'weather': 'हवामान',
      'detecting_address': 'पत्ता शोधला जात आहे...',
      'no_active_alerts': 'सध्या कोणतेही अलर्ट नाहीत. सुरक्षित रहा!',
      'alert': 'अलर्ट',
      'info': 'माहिती',
      'details_unavailable': 'तपशील उपलब्ध नाही.',
      'weather_data_unavailable': 'नवीनतम हवामान डेटा उपलब्ध नाही.',
      'rain': 'पाऊस',
      'safe_status': 'सुरक्षित',
      'caution_status': 'सावध',
      'danger_status': 'धोका',
      'updating': 'अद्यतनित होत आहे...',
      'unknown': 'अज्ञात',
      'calculating': 'गणना सुरू आहे...',
      'detecting': 'शोधले जात आहे...',
      'moments_ago': 'काही क्षणांपूर्वी',
      'just_now': 'आत्ताच',
      'minutes_ago_suffix': 'मि.पूर्वी',
      'hours_ago_suffix': 'ता.पूर्वी',
      'days_ago_suffix': 'दिवसांपूर्वी',
      'entered_zone_title': 'क्षेत्रात प्रवेश',
      'entered_zone_message': 'आपण प्रवेश केला',
      'tourist_zone': 'पर्यटन क्षेत्र',
      'market_area': 'बाजार परिसर',
      'remote_forest': 'दूरस्थ जंगल',
      'local_police_station': 'स्थानिक पोलीस ठाणे',
      'sos_alert': 'एसओएस चेतावणी',
      'sos_dialog_message': 'आपण धोक्यात आहात का? हे आपत्कालीन सेवांना सूचित करेल.',
      'send_sos': 'एसओएस पाठवा',
      'sos_sent': 'एसओएस चेतावणी पाठवली!',
      'brief_title_hint': 'घटनेचे संक्षिप्त शीर्षक',
      'enter_incident_title': 'कृपया घटना शीर्षक भरा',
      'select_category': 'कृपया श्रेणी निवडा',
      'select_urgency': 'कृपया आपत्कालीन स्तर निवडा',
      'description_hint': 'घटनेचे सविस्तर वर्णन द्या',
      'enter_description': 'कृपया वर्णन भरा',
      'description_min': 'वर्णन किमान 10 अक्षरे असावे',
      'update_location': 'स्थान अद्यतनित करा',
      'getting_location': 'स्थान मिळवत आहोत...',
      'error_getting_location': 'सध्याचे स्थान मिळवताना त्रुटी',
      'incident_id_label': 'घटना आयडी',
      'incident_report_success': 'आपली घटना नोंदवली गेली आहे आणि अधिकाऱ्यांना सूचित केले गेले आहे.',
      'report_info': '📢 आपला अहवाल त्वरित स्थानिक अधिकाऱ्यांना पाठवला जाईल. अतिरिक्त माहितीसाठी ते आपल्याशी संपर्क साधू शकतात. संदर्भासाठी आपला घटना आयडी जतन करून ठेवा.',
      'theft': 'चोरी',
      'assault': 'हल्ला',
      'medical_emergency': 'वैद्यकीय आपत्काल',
      'accident': 'अपघात',
      'missing_person': 'हरवलेला व्यक्ती',
      'suspicious_activity': 'संशयास्पद हालचाल',
      'other': 'इतर',
    },
    'te': {
      // Dashboard
      'dashboard': 'డాష్‌బోర్డు',
      'safety_score': 'భద్రతా స్కోరు',
      'current_location': 'ప్రస్తుత స్థానం',
      'nearby_zones': 'సమీప ప్రాంతాలు',
      'active_alerts': 'సక్రియ హెచ్చరికలు',
      
      // Profile
      'profile': 'ప్రొఫైల్',
      'edit_profile': 'ప్రొఫైల్ సవరించండి',
      'name': 'పేరు',
      'email': 'ఇమెయిల్',
      'phone': 'ఫోన్',
      'country': 'దేశం',
      'emergency_contacts': 'అత్యవసర పరిచయాలు',
      'member_since': 'సభ్యత్వం నుండి',
      
      // Explore
      'explore': 'అన్వేషించండి',
      'nearby_places': 'సమీప ప్రదేశాలు',
      'categories': 'వర్గాలు',
      'all': 'అన్నీ',
      'famous': 'ప్రసಿದ್ಧ',
      'food': 'ఆహారం',
      'adventure': 'సాహసం',
      'hidden_gems': 'దాగి ఉన్న రత్నాలు',
      
      // Emergency
      'emergency': 'అత్యవసర పరిస్థితి',
      'sos': 'ఎస్‌ఓఎస్',
      'press_and_hold': 'నొక్కి పట్టుకోండి',
      'police': 'పోలీసులు',
      'ambulance': 'అంబులెన్స్',
      'fire': 'అగ్నిమాపక శాఖ',
      'share_location': 'నా స్థానాన్ని పంచుకోండి',
      'call_police': 'పోలీసులకు కాల్ చేయండి',
      'report_incident': 'ఘటన నివేదించండి',
      
      // Incident Report
      'incident_report': 'ఘటన నివేదిక',
      'incident_title': 'ఘటన శీర్షిక',
      'category': 'వర్గం',
      'urgency_level': 'అత్యవసర స్థాయి',
      'description': 'వివరణ',
      'location': 'స్థానం',
      'submit_report': 'నివేదిక సమర్పించండి',
      'incident_reported': 'ఘటన నివేదించబడింది',
      'low': 'తక్కువ',
      'medium': 'మధ్యస్థ',
      'high': 'ఎక్కువ',
      'critical': 'తీవ్ర',
      
      // Settings
      'settings': 'సెట్టింగులు',
      'language': 'భాష',
      'notifications': 'నోటిఫికేషన్‌లు',
      'enable_notifications': 'నోటిఫికేషన్‌లు ప్రారంభించండి',
      'dark_mode': 'డార్క్ మోడ్',
      'location_tracking': 'స్థానం ట్రాకింగ్',
      'enable_location_tracking': 'స్థానం ట్రాకింగ్ ప్రారంభించండి',
      'about': 'గురించి',
      'version': 'వెర్షన్',
      'logout': 'లాగ్ అవుట్',
      
      // Common
      'ok': 'సరే',
      'cancel': 'రద్దు',
      'save': 'సేవ్ చేయండి',
      'delete': 'తొలగించండి',
      'edit': 'సవరించండి',
      'add': 'జోడించండి',
      'close': 'మూసివేయండి',
      'loading': 'లోడ్ అవుతోంది...',
      'error': 'లోపం',
      'success': 'విజయం',
      'no_data': 'డేటా లేదు',
      'place': 'స్థలం',
      'distance': 'దూరం',
      'view_details': 'వివరాలు చూడండి',
      'out_of_100': '100 లో',
      'current_zone': 'ప్రస్తుత ప్రాంతం',
      'time': 'సమయం',
      'crowd_density': 'జనసాంద్రత',
      'weather': 'వాతావరణం',
      'detecting_address': 'చిరునామా పొందుతున్నాం...',
      'no_active_alerts': 'ప్రస్తుతం ఎలాంటి అలర్ట్లు లేవు. సురక్షితంగా ఉండండి!',
      'alert': 'హెచ్చరిక',
      'info': 'సమాచారం',
      'details_unavailable': 'వివరాలు అందుబాటులో లేవు.',
      'weather_data_unavailable': 'తాజా వాతావరణ డేటా అందుబాటులో లేదు.',
      'rain': 'వర్షం',
      'safe_status': 'సురక్షితం',
      'caution_status': 'హెచ్చరిక',
      'danger_status': 'అపాయం',
      'updating': 'నవీకరిస్తోంది...',
      'unknown': 'తెలియదు',
      'calculating': 'లెక్కించబడుతోంది...',
      'detecting': 'కనుగొంటోంది...',
      'moments_ago': 'కొన్ని క్షణాల క్రితం',
      'just_now': 'ఇప్పుడే',
      'minutes_ago_suffix': 'ని. క్రితం',
      'hours_ago_suffix': 'గం. క్రితం',
      'days_ago_suffix': 'రోజుల క్రితం',
      'entered_zone_title': 'ప్రాంతంలోకి ప్రవేశించారు',
      'entered_zone_message': 'మీరు ప్రవేశించారు',
      'tourist_zone': 'పర్యాటక ప్రాంతం',
      'market_area': 'మార్కెట్ ప్రాంతం',
      'remote_forest': 'దూరపు అరణ్యం',
      'local_police_station': 'స్థానిక పోలీస్ స్టేషన్',
      'sos_alert': 'SOS హెచ్చరిక',
      'sos_dialog_message': 'మీరు ప్రమాదంలో ఉన్నారా? ఇది అత్యవసర సేవలను హెచ్చరిస్తుంది.',
      'send_sos': 'SOS పంపండి',
      'sos_sent': 'SOS హెచ్చరిక పంపబడింది!',
      'brief_title_hint': 'ఘటన యొక్క సంక్షిప్త శీర్షిక',
      'enter_incident_title': 'దయచేసి ఘటన శీర్షికను నమోదు చేయండి',
      'select_category': 'దయచేసి ఒక వర్గాన్ని ఎంచుకోండి',
      'select_urgency': 'దయచేసి అత్యవసర స్థాయిని ఎంచుకోండి',
      'description_hint': 'ఘటనకు సంబంధించిన పూర్తి వివరణ ఇవ్వండి',
      'enter_description': 'దయచేసి వివరణను నమోదు చేయండి',
      'description_min': 'వివరణ కనీసం 10 అక్షరాలు ఉండాలి',
      'update_location': 'స్థానం అప్డేట్ చేయండి',
      'getting_location': 'స్థానం పొందుతున్నాం...',
      'error_getting_location': 'ప్రస్తుత స్థానం పొందడంలో లోపం',
      'incident_id_label': 'ఘటన ID',
      'incident_report_success': 'మీ ఘటనను నివేదించాం మరియు అధికారులకు తెలియజేశాం.',
      'report_info': '📢 మీ నివేదిక తక్షణమే స్థానిక అధికారులకు పంపబడుతుంది. అదనపు వివరాల కోసం వారు మిమ్మల్ని సంప్రదించవచ్చు. సూచన కోసం మీ ఘటన IDని దగ్గర ఉంచండి.',
      'theft': 'దొంగతనం',
      'assault': 'దాడి',
      'medical_emergency': 'వైద్య అత్యవసర పరిస్థితి',
      'accident': 'అపఘాతం',
      'missing_person': 'అదృశ్యమైన వ్యక్తి',
      'suspicious_activity': 'సందేహాస్పద చర్య',
      'other': 'ఇతర',
    },
    'ta': {
      // Dashboard
      'dashboard': 'டாஷ்போர்டு',
      'safety_score': 'பாதுகாப்பு மதிப்பெண்',
      'current_location': 'தற்போதைய இடம்',
      'nearby_zones': 'அருகிலுள்ள பகுதிகள்',
      'active_alerts': 'செயலில் உள்ள எச்சரிக்கைகள்',
      
      // Profile
      'profile': 'சுயவிவரம்',
      'edit_profile': 'சுயவிவரத்தை திருத்தவும்',
      'name': 'பெயர்',
      'email': 'மின்னஞ்சல்',
      'phone': 'தொலைபேசி',
      'country': 'நாடு',
      'emergency_contacts': 'அவசர தொடர்புகள்',
      'member_since': 'உறுப்பினராக இருந்து',
      
      // Explore
      'explore': 'ஆராய்ந்து பார்க்க',
      'nearby_places': 'அருகிலுள்ள இடங்கள்',
      'categories': 'வகைகள்',
      'all': 'அனைத்தும்',
      'famous': 'புகழ்பெற்ற',
      'food': 'உணவு',
      'adventure': 'சாகசம்',
      'hidden_gems': 'மறைந்த ரத்தினங்கள்',
      
      // Emergency
      'emergency': 'அவசரம்',
      'sos': 'எஸ்.ஓ.எஸ்',
      'press_and_hold': 'அழுத்தி பிடிக்கவும்',
      'police': 'போலீஸ்',
      'ambulance': 'ஆம்புலன்ஸ்',
      'fire': 'தீயணைப்பு துறை',
      'share_location': 'என் இருப்பிடத்தை பகிர்',
      'call_police': 'போலீஸை அழைக்கவும்',
      'report_incident': 'சம்பவத்தை அறிவிக்கவும்',
      
      // Incident Report
      'incident_report': 'சம்பவ அறிக்கை',
      'incident_title': 'சம்பவ தலைப்பு',
      'category': 'வகை',
      'urgency_level': 'அவசர நிலை',
      'description': 'விளக்கம்',
      'location': 'இடம்',
      'submit_report': 'அறிக்கையை சமர்ப்பிக்கவும்',
      'incident_reported': 'சம்பவம் தெரிவிக்கப்பட்டது',
      'low': 'குறைவு',
      'medium': 'நடுத்தரம்',
      'high': 'அதிகம்',
      'critical': 'முக்கியம்',
      
      // Settings
      'settings': 'அமைப்புகள்',
      'language': 'மொழி',
      'notifications': 'அறிவிப்புகள்',
      'enable_notifications': 'அறிவிப்புகளை இயக்கவும்',
      'dark_mode': 'இருண்ட பயன்முறை',
      'location_tracking': 'இருப்பிட கண்காணிப்பு',
      'enable_location_tracking': 'இருப்பிட கண்காணிப்பை இயக்கவும்',
      'about': 'பற்றி',
      'version': 'பதிப்பு',
      'logout': 'வெளியேறு',
      
      // Common
      'ok': 'சரி',
      'cancel': 'ரத்து செய்',
      'save': 'சேமிக்கவும்',
      'delete': 'நீக்கு',
      'edit': 'திருத்து',
      'add': 'சேர்க்க',
      'close': 'மூடு',
      'loading': 'ஏற்றப்படுகிறது...',
      'error': 'பிழை',
      'success': 'வெற்றி',
      'no_data': 'தரவு இல்லை',
      'place': 'இடம்',
      'distance': 'தூரம்',
      'view_details': 'விவரங்களை காண்க',
      'out_of_100': '100 இல்',
      'current_zone': 'தற்போதைய பகுதி',
      'time': 'நேரம்',
      'crowd_density': 'கூட்டம் அடர்த்தி',
      'weather': 'வானிலை',
      'detecting_address': 'முகவரி கண்டறியப்படுகிறது...',
      'no_active_alerts': 'இப்போது செயல்பாட்டில் எச்சரிக்கைகள் இல்லை. பாதுகாப்பாக இருங்கள்!',
      'alert': 'எச்சரிக்கை',
      'info': 'தகவல்',
      'details_unavailable': 'விவரங்கள் கிடைக்கவில்லை.',
      'weather_data_unavailable': 'சமீபத்திய வானிலை தரவு கிடைக்கவில்லை.',
      'rain': 'மழை',
      'safe_status': 'பாதுகாப்பானது',
      'caution_status': 'எச்சரிக்கை',
      'danger_status': 'அபயம்',
      'updating': 'புதுப்பிக்கப்படுகிறது...',
      'unknown': 'அறியப்படாதது',
      'calculating': 'கணக்கிடப்படுகிறது...',
      'detecting': 'கண்டறியப்படுகிறது...',
      'moments_ago': 'சிறிது நேரம் முன்',
      'just_now': 'இப்போதுதான்',
      'minutes_ago_suffix': 'நிமி முன்',
      'hours_ago_suffix': 'மணி முன்',
      'days_ago_suffix': 'நாட்களுக்கு முன்',
      'entered_zone_title': 'பகுதியில் நுழைந்தீர்கள்',
      'entered_zone_message': 'நீங்கள் நுழைந்துள்ளீர்கள்',
      'tourist_zone': 'சுற்றுலா பகுதி',
      'market_area': 'சந்தை பகுதி',
      'remote_forest': 'தொலைதூரக் காடு',
      'local_police_station': 'உள்ளூர் காவல் நிலையம்',
      'sos_alert': 'SOS எச்சரிக்கை',
      'sos_dialog_message': 'நீங்கள் ஆபத்தில் உள்ளீர்களா? இது அவசர சேவைகளை எச்சரிக்கும்.',
      'send_sos': 'SOS அனுப்புக',
      'sos_sent': 'SOS எச்சரிக்கை அனுப்பப்பட்டது!',
      'brief_title_hint': 'சம்பவத்தின் சுருக்க தலைப்பு',
      'enter_incident_title': 'சம்பவத்தின் தலைப்பை உள்ளிடவும்',
      'select_category': 'தயவு செய்து ஒரு வகையைத் தேர்ந்தெடுக்கவும்',
      'select_urgency': 'தயவு செய்து அவசர நிலையைத் தேர்ந்தெடுக்கவும்',
      'description_hint': 'சம்பவத்தின் விரிவான விளக்கத்தை வழங்கவும்',
      'enter_description': 'விளக்கத்தை உள்ளிடவும்',
      'description_min': 'விளக்கம் குறைந்தது 10 எழுத்துகள் இருக்க வேண்டும்',
      'update_location': 'இருப்பிடத்தை புதுப்பிக்கவும்',
      'getting_location': 'இருப்பிடம் பெறப்படுகிறது...',
      'error_getting_location': 'தற்போதைய இருப்பிடத்தை பெறும்போது பிழை',
      'incident_id_label': 'சம்பவ ID',
      'incident_report_success': 'உங்கள் சம்பவம் பதிவு செய்யப்பட்டு அதிகாரிகளுக்கு அறிவிக்கப்பட்டுள்ளது.',
      'report_info': '📢 உங்கள் புகார் உடனடியாக உள்ளூர் அதிகாரிகளிடம் அனுப்பப்படும். கூடுதல் தகவலுக்காக அவர்கள் உங்களை தொடர்பு கொள்ளலாம். உதவிக்குறிப்பாக சம்பவ ID -ஐ வைத்திருக்கவும்.',
      'theft': 'கள்வி',
      'assault': 'தாக்குதல்',
      'medical_emergency': 'மருத்துவ அவசரம்',
      'accident': 'விபத்து',
      'missing_person': 'காணாமல் போனவர்',
      'suspicious_activity': 'சந்தேகமான செயல்',
      'other': 'மற்றவை',
    },
    'gu': {
      // Dashboard
      'dashboard': 'ડેશબોર્ડ',
      'safety_score': 'સુરક્ષા સ્કોર',
      'current_location': 'વર્તમાન સ્થાન',
      'nearby_zones': 'નજીકના ઝોન',
      'active_alerts': 'સક્રિય ચેતવણીઓ',
      
      // Profile
      'profile': 'પ્રોફાઇલ',
      'edit_profile': 'પ્રોફાઇલ સંપાદિત કરો',
      'name': 'નામ',
      'email': 'ઇમેઇલ',
      'phone': 'ફોન',
      'country': 'દેશ',
      'emergency_contacts': 'ઇમર્જન્સી સંપર્કો',
      'member_since': 'સદસ્ય ત્યારથી',
      
      // Explore
      'explore': 'શોધો',
      'nearby_places': 'નજીકના સ્થળો',
      'categories': 'શ્રેણીઓ',
      'all': 'બધા',
      'famous': 'પ્રસિદ્ધ',
      'food': 'ભોજન',
      'adventure': 'સાહસ',
      'hidden_gems': 'છૂપાયેલા રત્નો',
      
      // Emergency
      'emergency': 'ઇમર્જન્સી',
      'sos': 'SOS',
      'press_and_hold': 'દબાવો અને રાખો',
      'police': 'પોલીસ',
      'ambulance': 'એમ્બ્યુલન્સ',
      'fire': 'ફાયર વિભાગ',
      'share_location': 'મારું સ્થાન શેર કરો',
      'call_police': 'પોલીસને કૉલ કરો',
      'report_incident': 'ઘટનાની જાણ કરો',
      
      // Incident Report
      'incident_report': 'ઘટના રિપોર્ટ',
      'incident_title': 'ઘટનાનો શીર્ષક',
      'category': 'શ્રેણી',
      'urgency_level': 'તાત્કાલિક સ્તર',
      'description': 'વર્ણન',
      'location': 'સ્થાન',
      'submit_report': 'રિપોર્ટ સબમિટ કરો',
      'incident_reported': 'ઘટના નોંધાઈ',
      'low': 'ઓછું',
      'medium': 'મધ્યમ',
      'high': 'ઊંચું',
      'critical': 'ગંભીર',
      
      // Settings
      'settings': 'સેટિંગ્સ',
      'language': 'ભાષા',
      'notifications': 'સૂચનાઓ',
      'enable_notifications': 'સૂચનાઓ સક્રિય કરો',
      'dark_mode': 'ડાર્ક મોડ',
      'location_tracking': 'સ્થાન ટ્રેકિંગ',
      'enable_location_tracking': 'સ્થાન ટ્રેકિંગ સક્રિય કરો',
      'about': 'વિશે',
      'version': 'વર્ઝન',
      'logout': 'લોગ આઉટ',
      
      // Common
      'ok': 'ઠીક છે',
      'cancel': 'રદ કરો',
      'save': 'સાચવો',
      'delete': 'કાઢી નાખો',
      'edit': 'સંપાદિત કરો',
      'add': 'ઉમેરો',
      'close': 'બંધ કરો',
      'loading': 'લોડ થઈ રહ્યું છે...',
      'error': 'ભૂલ',
      'success': 'સફળતા',
      'no_data': 'કોઈ ડેટા ઉપલબ્ધ નથી',
      'place': 'સ્થળ',
      'distance': 'અંતર',
      'view_details': 'વિગતો જુઓ',
      'out_of_100': '100 માંથી',
      'current_zone': 'વર્તમાન ઝોન',
      'time': 'સમય',
      'crowd_density': 'ભીડની ઘનતા',
      'weather': 'હવામાન',
      'detecting_address': 'સરનામું શોધી રહ્યા છીએ...',
      'no_active_alerts': 'હાલમાં કોઈ સક્રિય સૂચનાઓ નથી. સુરક્ષિત રહો!',
      'alert': 'ચેતવણી',
      'info': 'માહિતી',
      'details_unavailable': 'વિગતો ઉપલબ્ધ નથી.',
      'weather_data_unavailable': 'તાજેતરનું હવામાન ડેટા ઉપલબ્ધ નથી.',
      'rain': 'વરસાદ',
      'safe_status': 'સુરક્ષિત',
      'caution_status': 'ચેતવણી',
      'danger_status': 'ખતરો',
      'updating': 'અપડેટ કરી રહ્યા છીએ...',
      'unknown': 'અજ્ઞાત',
      'calculating': 'ગણતરી થઈ રહી છે...',
      'detecting': 'શોધી રહ્યા છીએ...',
      'moments_ago': 'થોડા ક્ષણો પહેલા',
      'just_now': 'હમણાં જ',
      'minutes_ago_suffix': 'મિનિટ પહેલા',
      'hours_ago_suffix': 'કલાક પહેલા',
      'days_ago_suffix': 'દિવસ પહેલા',
      'entered_zone_title': 'ઝોનમાં દાખલ થયા',
      'entered_zone_message': 'તમે પ્રવેશ કર્યો છે',
      'tourist_zone': 'પર્યટક વિસ્તાર',
      'market_area': 'માર્કેટ વિસ્તાર',
      'remote_forest': 'દૂરનું જંગલ',
      'local_police_station': 'સ્થાનિક પોલીસ સ્ટેશન',
      'sos_alert': 'SOS ચેતવણી',
      'sos_dialog_message': 'શું તમે જોખમમાં છો? આ તાત્કાલિક સેવાઓને ચેતવણી આપશે.',
      'send_sos': 'SOS મોકલો',
      'sos_sent': 'SOS ચેતવણી મોકલાઈ!',
      'brief_title_hint': 'ઘટનાનો સંક્ષિપ્ત શીર્ષક',
      'enter_incident_title': 'કૃપા કરીને ઘટના શીર્ષક દાખલ કરો',
      'select_category': 'કૃપા કરીને શ્રેણી પસંદ કરો',
      'select_urgency': 'કૃપા કરીને તાત્કાલિક સ્તર પસંદ કરો',
      'description_hint': 'ઘટનાનું વિગતવાર વર્ણન આપો',
      'enter_description': 'કૃપા કરીને વર્ણન દાખલ કરો',
      'description_min': 'વર્ણન ઓછામાં ઓછું 10 અક્ષરોનું હોવું જોઈએ',
      'update_location': 'સ્થાન અપડેટ કરો',
      'getting_location': 'સ્થાન મેળવી રહ્યાં છીએ...',
      'error_getting_location': 'વર્તમાન સ્થાન મેળવવામાં ભૂલ',
      'incident_id_label': 'ઘટના ID',
      'incident_report_success': 'તમારી ઘટના નોંધાઈ છે અને સત્તાવાળાઓને સૂચના આપવામાં આવી છે.',
      'report_info': '📢 તમારો રિપોર્ટ તરત જ સ્થાનિક સત્તાવાળાઓને મોકલાશે. વધારાની માહિતી માટે તેઓ તમારા સંપર્કમાં આવી શકે છે. સંદર્ભ માટે તમારી ઘટના ID રાખો.',
      'theft': 'ચોરી',
      'assault': 'હુમલો',
      'medical_emergency': 'વૈદ્યકીય તાત્કાલિક સેવા',
      'accident': 'આપઘાત',
      'missing_person': 'ગુમ વ્યક્તિ',
      'suspicious_activity': 'શંકાસ્પદ પ્રવૃત્તિ',
      'other': 'અન્ય',
    },
    'ur': {
      // Dashboard
      'dashboard': 'ڈیش بورڈ',
      'safety_score': 'حفاظت اسکور',
      'current_location': 'موجودہ مقام',
      'nearby_zones': 'قریبی علاقے',
      'active_alerts': 'فعال انتباہات',
      
      // Profile
      'profile': 'پروفائل',
      'edit_profile': 'پروفائل میں ترمیم کریں',
      'name': 'نام',
      'email': 'ای میل',
      'phone': 'فون',
      'country': 'ملک',
      'emergency_contacts': 'ایمرجنسی رابطے',
      'member_since': 'رکن بننے سے',
      
      // Explore
      'explore': 'دریافت کریں',
      'nearby_places': 'قریبی مقامات',
      'categories': 'زمرے',
      'all': 'سب',
      'famous': 'مشہور',
      'food': 'خوراک',
      'adventure': 'مہم جوئی',
      'hidden_gems': 'پوشیدہ نگینے',
      
      // Emergency
      'emergency': 'ہنگامی حالت',
      'sos': 'ایس او ایس',
      'press_and_hold': 'دبائیں اور تھامیں',
      'police': 'پولیس',
      'ambulance': 'ایمبولینس',
      'fire': 'فائر ڈیپارٹمنٹ',
      'share_location': 'میرا مقام شیئر کریں',
      'call_police': 'پولیس کو کال کریں',
      'report_incident': 'واقعہ رپورٹ کریں',
      
      // Incident Report
      'incident_report': 'واقعہ رپورٹ',
      'incident_title': 'واقعہ کا عنوان',
      'category': 'زمرہ',
      'urgency_level': 'ہنگامی سطح',
      'description': 'تفصیل',
      'location': 'مقام',
      'submit_report': 'رپورٹ جمع کریں',
      'incident_reported': 'واقعہ رپورٹ کر دیا گیا',
      'low': 'کم',
      'medium': 'درمیانہ',
      'high': 'زیادہ',
      'critical': 'نازک',
      
      // Settings
      'settings': 'سیٹنگز',
      'language': 'زبان',
      'notifications': 'اطلاعات',
      'enable_notifications': 'اطلاعات فعال کریں',
      'dark_mode': 'ڈارک موڈ',
      'location_tracking': 'مقام کی نگرانی',
      'enable_location_tracking': 'مقام کی نگرانی فعال کریں',
      'about': 'کے بارے میں',
      'version': 'ورژن',
      'logout': 'لاگ آؤٹ',
      
      // Common
      'ok': 'ٹھیک ہے',
      'cancel': 'منسوخ کریں',
      'save': 'محفوظ کریں',
      'delete': 'حذف کریں',
      'edit': 'ترمیم کریں',
      'add': 'شامل کریں',
      'close': 'بند کریں',
      'loading': 'لوڈ ہو رہا ہے...',
      'error': 'خرابی',
      'success': 'کامیابی',
      'no_data': 'کوئی ڈیٹا دستیاب نہیں',
      'place': 'مقام',
      'distance': 'فاصلہ',
      'view_details': 'تفصیل دیکھیں',
      'out_of_100': '100 میں سے',
      'current_zone': 'موجودہ زون',
      'time': 'وقت',
      'crowd_density': 'ہجوم کی کثافت',
      'weather': 'موسم',
      'detecting_address': 'ایڈریس تلاش کیا جا رہا ہے...',
      'no_active_alerts': 'اس وقت کوئی فعال الرٹ نہیں۔ محفوظ رہیں!',
      'alert': 'الرٹ',
      'info': 'معلومات',
      'details_unavailable': 'تفصیلات دستیاب نہیں۔',
      'weather_data_unavailable': 'تازہ موسم کا ڈیٹا دستیاب نہیں۔',
      'rain': 'بارش',
      'safe_status': 'محفوظ',
      'caution_status': 'احتیاط',
      'danger_status': 'خطرہ',
      'updating': 'اپ ڈیٹ ہو رہا ہے...',
      'unknown': 'نامعلوم',
      'calculating': 'حساب لگایا جا رہا ہے...',
      'detecting': 'پتہ لگایا جا رہا ہے...',
      'moments_ago': 'کچھ دیر پہلے',
      'just_now': 'ابھی ابھی',
      'minutes_ago_suffix': 'منٹ پہلے',
      'hours_ago_suffix': 'گھنٹے پہلے',
      'days_ago_suffix': 'دن پہلے',
      'entered_zone_title': 'زون میں داخل',
      'entered_zone_message': 'آپ داخل ہوئے ہیں',
      'tourist_zone': 'سیاحتی علاقہ',
      'market_area': 'بازار علاقہ',
      'remote_forest': 'دور دراز جنگل',
      'local_police_station': 'مقامی تھانہ',
      'sos_alert': 'SOS الرٹ',
      'sos_dialog_message': 'کیا آپ خطرے میں ہیں؟ یہ ایمرجنسی سروسز کو مطلع کرے گا۔',
      'send_sos': 'SOS بھیجیں',
      'sos_sent': 'SOS الرٹ بھیج دیا گیا!',
      'brief_title_hint': 'واقعہ کا مختصر عنوان',
      'enter_incident_title': 'براہ کرم واقعہ کا عنوان درج کریں',
      'select_category': 'براہ کرم کوئی زمرہ منتخب کریں',
      'select_urgency': 'براہ کرم ہنگامی سطح منتخب کریں',
      'description_hint': 'واقعہ کی تفصیلی وضاحت فراہم کریں',
      'enter_description': 'براہ کرم وضاحت درج کریں',
      'description_min': 'وضاحت کم از کم 10 حروف پر مشتمل ہونی چاہیے',
      'update_location': 'مقام اپ ڈیٹ کریں',
      'getting_location': 'مقام حاصل کیا جا رہا ہے...',
      'error_getting_location': 'موجودہ مقام حاصل کرنے میں خرابی',
      'incident_id_label': 'واقعہ آئی ڈی',
      'incident_report_success': 'آپ کا واقعہ رپورٹ کر دیا گیا ہے اور حکام کو مطلع کر دیا گیا ہے۔',
      'report_info': '📢 آپ کی رپورٹ فوراً مقامی حکام کو بھیج دی جائے گی۔ اضافی معلومات کے لیے وہ آپ سے رابطہ کر سکتے ہیں۔ حوالہ کے لیے اپنی واقعہ آئی ڈی محفوظ رکھیں۔',
      'theft': 'چوری',
      'assault': 'حملہ',
      'medical_emergency': 'طبی ایمرجنسی',
      'accident': 'حادثہ',
      'missing_person': 'لاپتہ شخص',
      'suspicious_activity': 'مشکوک سرگرمی',
      'other': 'دیگر',
    },
    'kn': {
      // Dashboard
      'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'safety_score': 'ಸುರಕ್ಷತಾ ಅಂಕ',
      'current_location': 'ಪ್ರಸ್ತುತ ಸ್ಥಳ',
      'nearby_zones': 'ಹತ್ತಿರದ ವಲಯಗಳು',
      'active_alerts': 'ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳು',
      
      // Profile
      'profile': 'ಪ್ರೊಫೈಲ್',
      'edit_profile': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
      'name': 'ಹೆಸರು',
      'email': 'ಇಮೇಲ್',
      'phone': 'ಫೋನ್',
      'country': 'ದೇಶ',
      'emergency_contacts': 'ತುರ್ತು ಸಂಪರ್ಕಗಳು',
      'member_since': 'ಸದಸ್ಯರಾದಿನಿಂದ',
      
      // Explore
      'explore': 'ಅನ್ವೇಷಿಸಿ',
      'nearby_places': 'ಸಮೀಪದ ಸ್ಥಳಗಳು',
      'categories': 'ವರ್ಗಗಳು',
      'all': 'ಎಲ್ಲಾ',
      'famous': 'ಪ್ರಸಿದ್ಧ',
      'food': 'ಆಹಾರ',
      'adventure': 'ಸಾಹಸ',
      'hidden_gems': 'ಮರೆವಾದ ರತ್ನಗಳು',
      
      // Emergency
      'emergency': 'ತುರ್ತು ಪರಿಸ್ಥಿತಿ',
      'sos': 'ಎಸ್‌ಒಎಸ್',
      'press_and_hold': 'ಒತ್ತಿ ಹಿಡಿದುಕೊಳ್ಳಿ',
      'police': 'ಪೊಲೀಸ್',
      'ambulance': 'ಆಂಬ್ಯುಲೆನ್ಸ್',
      'fire': 'ಅಗ್ನಿಶಾಮಕ ಇಲಾಖೆ',
      'share_location': 'ನನ್ನ ಸ್ಥಳವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
      'call_police': 'ಪೊಲೀಸ್‌ಗೆ ಕರೆ ಮಾಡಿ',
      'report_incident': 'ಘಟನೆ ವರದಿ ಮಾಡಿ',
      
      // Incident Report
      'incident_report': 'ಘಟನೆ ವರದಿ',
      'incident_title': 'ಘಟನೆಯ ಶೀರ್ಷಿಕೆ',
      'category': 'ವರ್ಗ',
      'urgency_level': 'ತುರ್ತು ಮಟ್ಟ',
      'description': 'ವಿವರಣೆ',
      'location': 'ಸ್ಥಳ',
      'submit_report': 'ವರದಿಯನ್ನು ಸಲ್ಲಿಸಿ',
      'incident_reported': 'ಘಟನೆ ವರದಿಯಾಯಿತು',
      'low': 'ಕಡಿಮೆ',
      'medium': 'ಮಧ್ಯಮ',
      'high': 'ಹೆಚ್ಚು',
      'critical': 'ಗಂಭೀರ',
      
      // Settings
      'settings': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
      'language': 'ಭಾಷೆ',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'enable_notifications': 'ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ',
      'dark_mode': 'ಕತ್ತಲೆ ಮೋಡ್',
      'location_tracking': 'ಸ್ಥಳ ಟ್ರ್ಯಾಕಿಂಗ್',
      'enable_location_tracking': 'ಸ್ಥಳ ಟ್ರ್ಯಾಕಿಂಗ್ ಸಕ್ರಿಯಗೊಳಿಸಿ',
      'about': 'ಬಗ್ಗೆ',
      'version': 'ಆವೃತ್ತಿ',
      'logout': 'ಲಾಗ್ ಔಟ್',
      
      // Common
      'ok': 'ಸರಿ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'save': 'ಉಳಿಸಿ',
      'delete': 'ಅಳಿಸಿ',
      'edit': 'ಸಂಪಾದಿಸಿ',
      'add': 'ಸೇರಿಸಿ',
      'close': 'ಮುಚ್ಚಿ',
      'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      'error': 'ದೋಷ',
      'success': 'ಯಶಸ್ಸು',
      'no_data': 'ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ',
      'place': 'ಸ್ಥಳ',
      'distance': 'ದೂರ',
      'view_details': 'ವಿವರಗಳನ್ನು ನೋಡಿ',
      'out_of_100': '100ರಲ್ಲಿ',
      'current_zone': 'ಪ್ರಸ್ತುತ ವಲಯ',
      'time': 'ಸಮಯ',
      'crowd_density': 'ಗಿರಾಕಿಗಳ ಸಾಂದ್ರತೆ',
      'weather': 'ಹವಾಮಾನ',
      'detecting_address': 'ವಿಳಾಸ ಪತ್ತೆ ಮಾಡಲಾಗುತ್ತಿದೆ...',
      'no_active_alerts': 'ಪ್ರಸ್ತುತ ಯಾವುದೇ ಅಲರ್ಟ್ ಇಲ್ಲ. ಸುರಕ್ಷಿತವಾಗಿರಿ!',
      'alert': 'ಎಚ್ಚರಿಕೆ',
      'info': 'ಮಾಹಿತಿ',
      'details_unavailable': 'ವಿವರಗಳು ಲಭ್ಯವಿಲ್ಲ.',
      'weather_data_unavailable': 'ಇತ್ತೀಚಿನ ಹವಾಮಾನ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ.',
      'rain': 'ಮಳೆ',
      'safe_status': 'ಸುರಕ್ಷಿತ',
      'caution_status': 'ಎಚ್ಚರಿಕೆ',
      'danger_status': 'ಅಪಾಯ',
      'updating': 'ನವೀಕರಿಸಲಾಗುತ್ತಿದೆ...',
      'unknown': 'ಅಪರಿಚಿತ',
      'calculating': 'ಲೆಕ್ಕಿಸಲಾಗುತ್ತಿದೆ...',
      'detecting': 'ಪತ್ತೆ ಮಾಡಲಾಗುತ್ತಿದೆ...',
      'moments_ago': 'ಸ್ವಲ್ಪ ಕ್ಷಣಗಳ ಹಿಂದೆ',
      'just_now': 'ಇದೀಗ',
      'minutes_ago_suffix': 'ನಿಮಿ ಹಿಂದೆ',
      'hours_ago_suffix': 'ಗಂ ಹಿಂದೆ',
      'days_ago_suffix': 'ದಿನ ಹಿಂದೆ',
      'entered_zone_title': 'ವಲಯಕ್ಕೆ ಪ್ರವೇಶಿಸಲಾಗಿದೆ',
      'entered_zone_message': 'ನೀವು ಪ್ರವೇಶಿಸಿದ್ದೀರಿ',
      'tourist_zone': 'ಪರ್ಯಟಕ ವಲಯ',
      'market_area': 'ಮಾರ್ಕೆಟ್ ಪ್ರದೇಶ',
      'remote_forest': 'ದೂರದ ಕಾಡು',
      'local_police_station': 'ಸ್ಥಳೀಯ ಪೊಲೀಸ್ ಠಾಣೆ',
      'sos_alert': 'SOS ಎಚ್ಚರಿಕೆ',
      'sos_dialog_message': 'ನೀವು ಅಪಾಯದಲ್ಲಿದ್ದೀರಾ? ಇದು ತುರ್ತು ಸೇವೆಗಳಿಗೆ ಎಚ್ಚರಿಕೆ ನೀಡುತ್ತದೆ.',
      'send_sos': 'SOS ಕಳುಹಿಸಿ',
      'sos_sent': 'SOS ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಲಾಗಿದೆ!',
      'brief_title_hint': 'ಘಟನೆಯ ಸಂಕ್ಷಿಪ್ತ ಶೀರ್ಷಿಕೆ',
      'enter_incident_title': 'ದಯವಿಟ್ಟು ಘಟನೆಯ ಶೀರ್ಷಿಕೆಯನ್ನು ನಮೂದಿಸಿ',
      'select_category': 'ದಯವಿಟ್ಟು ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'select_urgency': 'ದಯವಿಟ್ಟು ತುರ್ತು ಮಟ್ಟವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'description_hint': 'ಘಟನೆಯ ವಿವರವಾದ ವಿವರಣೆಯನ್ನು ನೀಡಿ',
      'enter_description': 'ದಯವಿಟ್ಟು ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ',
      'description_min': 'ವಿವರಣೆ ಕನಿಷ್ಠ 10 ಅಕ್ಷರಗಳಿರಬೇಕು',
      'update_location': 'ಸ್ಥಳವನ್ನು ನವೀಕರಿಸಿ',
      'getting_location': 'ಸ್ಥಳವನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ...',
      'error_getting_location': 'ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಪಡೆಯುವಲ್ಲಿ ದೋಷ',
      'incident_id_label': 'ಘಟನೆ ID',
      'incident_report_success': 'ನಿಮ್ಮ ಘಟನೆ ವರದಿಯಾಗಿದೆ ಮತ್ತು ಅಧಿಕಾರಿಗಳಿಗೆ ತಿಳಿಸಲಾಗಿದೆ.',
      'report_info': '📢 ನಿಮ್ಮ ವರದಿ ತಕ್ಷಣವೇ ಸ್ಥಳೀಯ ಅಧಿಕಾರಿಗಳಿಗೆ ಕಳುಹಿಸಲಾಗುತ್ತದೆ. ಹೆಚ್ಚುವರಿ ಮಾಹಿತಿಗಾಗಿ ಅವರು ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಬಹುದು. ಉಲ್ಲೇಖಕ್ಕಾಗಿ ನಿಮ್ಮ ಘಟನೆ ID ಉಳಿಸಿಕೊಳ್ಳಿ.',
      'theft': 'ಕಳ್ಳತನ',
      'assault': 'ಹಲ್ಲೆ',
      'medical_emergency': 'ವೈದ್ಯಕೀಯ ತುರ್ತು ಪರಿಸ್ಥಿತಿ',
      'accident': 'ಅಪಘಾತ',
      'missing_person': 'ಕಾಣೆಯಾದ ವ್ಯಕ್ತಿ',
      'suspicious_activity': 'ಸಂದೇಹಾಸ್ಪದ ಚಟುವಟಿಕೆ',
      'other': 'ಇತರೆ',
    },
    'or': {
      // Dashboard
      'dashboard': 'ଡ୍ୟାଶବୋର୍ଡ',
      'safety_score': 'ସୁରକ୍ଷା ସ୍କୋର',
      'current_location': 'ବର୍ତ୍ତମାନ ସ୍ଥାନ',
      'nearby_zones': 'ନିକଟସ୍ଥ କ୍ଷେତ୍ର',
      'active_alerts': 'ସକ୍ରିୟ ସତର୍କତା',
      
      // Profile
      'profile': 'ପ୍ରୋଫାଇଲ',
      'edit_profile': 'ପ୍ରୋଫାଇଲ ସମ୍ପାଦନ କରନ୍ତୁ',
      'name': 'ନାମ',
      'email': 'ଇମେଲ',
      'phone': 'ଫୋନ',
      'country': 'ଦେଶ',
      'emergency_contacts': 'ଜରୁରୀ ସଂପର୍କ',
      'member_since': 'ସଦସ୍ୟ ଥିବା ସମୟରୁ',
      
      // Explore
      'explore': 'ଅନୁସନ୍ଧାନ କରନ୍ତୁ',
      'nearby_places': 'ନିକଟସ୍ଥ ସ୍ଥାନଗୁଡ଼ିକ',
      'categories': 'ଶ୍ରେଣୀ',
      'all': 'ସମସ୍ତ',
      'famous': 'ପ୍ରସିଦ୍ଧ',
      'food': 'ଖାଦ୍ୟ',
      'adventure': 'ରୋମାଞ୍ଚ',
      'hidden_gems': 'ଲୁଚା ରତ୍ନ',
      
      // Emergency
      'emergency': 'ଜରୁରୀ',
      'sos': 'ଏସଓଏସ',
      'press_and_hold': 'ଦବାନ୍ତୁ ଏବଂ ଧରନ୍ତୁ',
      'police': 'ପୁଲିସ',
      'ambulance': 'ଆମ୍ବୁଲାନ୍ସ',
      'fire': 'ଅଗ୍ନିଶମ ବିଭାଗ',
      'share_location': 'ମୋର ସ୍ଥାନ ସେୟାର କରନ୍ତୁ',
      'call_police': 'ପୁଲିସକୁ ଫୋନ କରନ୍ତୁ',
      'report_incident': 'ଘଟଣା ରିପୋର୍ଟ କରନ୍ତୁ',
      
      // Incident Report
      'incident_report': 'ଘଟଣା ରିପୋର୍ଟ',
      'incident_title': 'ଘଟଣାର ଶିରୋନାମ',
      'category': 'ଶ୍ରେଣୀ',
      'urgency_level': 'ଜରୁରୀ ସ୍ତର',
      'description': 'ବିବରଣୀ',
      'location': 'ସ୍ଥାନ',
      'submit_report': 'ରିପୋର୍ଟ ଦାଖଲ କରନ୍ତୁ',
      'incident_reported': 'ଘଟଣା ରିପୋର୍ଟ ହୋଇଛି',
      'low': 'କମ୍',
      'medium': 'ମଧ୍ୟମ',
      'high': 'ଅଧିକ',
      'critical': 'ସଂକଟପୂର୍ଣ୍ଣ',
      
      // Settings
      'settings': 'ସେଟିଂସ୍',
      'language': 'ଭାଷା',
      'notifications': 'ବିଜ୍ଞପ୍ତି',
      'enable_notifications': 'ବିଜ୍ଞପ୍ତି ସକ୍ରିୟ କରନ୍ତୁ',
      'dark_mode': 'ଡାର୍କ ମୋଡ୍',
      'location_tracking': 'ସ୍ଥାନ ଟ୍ରାକିଂ',
      'enable_location_tracking': 'ସ୍ଥାନ ଟ୍ରାକିଂ ସକ୍ରିୟ କରନ୍ତୁ',
      'about': 'ବିଷୟରେ',
      'version': 'ସଂସ୍କରଣ',
      'logout': 'ଲଗ୍ ଆଉଟ୍',
      
      // Common
      'ok': 'ଠିକ୍ ଅଛି',
      'cancel': 'ବାତିଲ୍',
      'save': 'ସେଭ୍ କରନ୍ତୁ',
      'delete': 'ଡିଲିଟ୍ କରନ୍ତୁ',
      'edit': 'ସମ୍ପାଦନ କରନ୍ତୁ',
      'add': 'ଯୋଡନ୍ତୁ',
      'close': 'ବନ୍ଦ କରନ୍ତୁ',
      'loading': 'ଲୋଡ୍ ହେଉଛି...',
      'error': 'ତ୍ରୁଟି',
      'success': 'ସଫଳତା',
      'no_data': 'କୌଣସି ତଥ୍ୟ ନାହିଁ',
      'place': 'ସ୍ଥାନ',
      'distance': 'ଦୂରତା',
      'view_details': 'ବିସ୍ତୃତ ଦେଖନ୍ତୁ',
      'out_of_100': '100 ମଧ୍ୟରୁ',
      'current_zone': 'ବର୍ତ୍ତମାନ ଅଞ୍ଚଳ',
      'time': 'ସମୟ',
      'crowd_density': 'ଭିଡ଼ ଘନତା',
      'weather': 'ପାଗ',
      'detecting_address': 'ଠିକଣା ଖୋଜାଯାଉଛି...',
      'no_active_alerts': 'ସମ୍ପ୍ରତି କୌଣସି ସଚେତନତା ନାହିଁ। ସୁରକ୍ଷିତ ରୁହନ୍ତୁ!',
      'alert': 'ସତର୍କତା',
      'info': 'ସୂଚନା',
      'details_unavailable': 'ବିବରଣୀ ଉପଲବ୍ଧ ନାହିଁ।',
      'weather_data_unavailable': 'ସମ୍ପ୍ରତି ପାଗ ତଥ୍ୟ ନାହିଁ।',
      'rain': 'ବର୍ଷା',
      'safe_status': 'ନିରାପଦ',
      'caution_status': 'ସତର୍କ',
      'danger_status': 'ବିପଦ',
      'updating': 'ଅଦ୍ୟତନ ହେଉଛି...',
      'unknown': 'ଅଜ୍ଞାତ',
      'calculating': 'ଗଣନା ହେଉଛି...',
      'detecting': 'ସନ୍ଧାନ ହେଉଛି...',
      'moments_ago': 'କିଛି ସମୟ ପୂର୍ବରୁ',
      'just_now': 'ଏହିମାତ୍ର',
      'minutes_ago_suffix': 'ମିନିଟ୍ ପୂର୍ବରୁ',
      'hours_ago_suffix': 'ଘଣ୍ଟା ପୂର୍ବରୁ',
      'days_ago_suffix': 'ଦିନ ପୂର୍ବରୁ',
      'entered_zone_title': 'ଅଞ୍ଚଳରେ ପ୍ରବେଶ',
      'entered_zone_message': 'ଆପଣ ପ୍ରବେଶ କରିଛନ୍ତି',
      'tourist_zone': 'ପର୍ଯ୍ୟଟନ ଅଞ୍ଚଳ',
      'market_area': 'ବଜାର ଅଞ୍ଚଳ',
      'remote_forest': 'ଦୂରସ୍ଥ ଜଙ୍ଗଲ',
      'local_police_station': 'ସ୍ଥାନୀୟ ଥାନା',
      'sos_alert': 'SOS ସତର୍କତା',
      'sos_dialog_message': 'ଆପଣ ଆପଦରେ କି? ଏହା ଆପତ୍କାଳୀନ ସେବାକୁ ସଚେତନ କରିବ।',
      'send_sos': 'SOS ପଠାନ୍ତୁ',
      'sos_sent': 'SOS ସତର୍କତା ପଠାଯାଇଛି!',
      'brief_title_hint': 'ଘଟଣାର ସଂକ୍ଷିପ୍ତ ଶିରୋନାମ',
      'enter_incident_title': 'ଦୟାକରି ଘଟଣାର ଶିରୋନାମ ଲେଖନ୍ତୁ',
      'select_category': 'ଦୟାକରି ଏକ ଶ୍ରେଣୀ ଚୟନ କରନ୍ତୁ',
      'select_urgency': 'ଦୟାକରି ଜରୁରୀ ସ୍ତର ଚୟନ କରନ୍ତୁ',
      'description_hint': 'ଘଟଣାର ବିସ୍ତୃତ ବର୍ଣ୍ଣନା ଦିଅନ୍ତୁ',
      'enter_description': 'ଦୟାକରି ବର୍ଣ୍ଣନା ଲେଖନ୍ତୁ',
      'description_min': 'ବର୍ଣ୍ଣନା କମରେ କମ 10ଟି ଅକ୍ଷର ହେବା ଉଚିତ୍',
      'update_location': 'ସ୍ଥାନ ଅଦ୍ୟତନ କରନ୍ତୁ',
      'getting_location': 'ସ୍ଥାନ ଆଣାଯାଉଛି...',
      'error_getting_location': 'ବର୍ତ୍ତମାନ ସ୍ଥାନ ଆଣିବାରେ ତ୍ରୁଟି',
      'incident_id_label': 'ଘଟଣା ID',
      'incident_report_success': 'ଆପଣଙ୍କ ଘଟଣା ରିପୋର୍ଟ ହୋଇଛି ଏବଂ କର୍ତ୍ତୃପକ୍ଷଙ୍କୁ ଜଣାଇଦିଆଯାଇଛି।',
      'report_info': '📢 ଆପଣଙ୍କ ରିପୋର୍ଟ ତକ୍ଷଣାତ୍ ସ୍ଥାନୀୟ କର୍ତ୍ତୃପକ୍ଷଙ୍କୁ ପଠାଯିବ। ଅତିରିକ୍ତ ସୂଚନା ପାଇଁ ସେମାନେ ଆପଣଙ୍କ ସହିତ ଯୋଗାଯୋଗ କରିପାରନ୍ତି। ଉଦ୍ଧୃତ ପାଇଁ ଆପଣଙ୍କ ଘଟଣା ID ସୁରକ୍ଷିତ ରଖନ୍ତୁ।',
      'theft': 'ଚୋରି',
      'assault': 'ଆକ୍ରମଣ',
      'medical_emergency': 'ଚିକିତ୍ସା ଆପତ୍କାଳ',
      'accident': 'ଦୁର୍ଘଟଣା',
      'missing_person': 'ନିଖୋଜ ବ୍ୟକ୍ତି',
      'suspicious_activity': 'ସନ୍ଦିଗ୍ଧ କାର୍ଯ୍ୟକଳାପ',
      'other': 'ଅନ୍ୟାନ୍ୟ',
    },
    'ml': {
      // Dashboard
      'dashboard': 'ഡാഷ്‌ബോർഡ്',
      'safety_score': 'സുരക്ഷാ സ്കോർ',
      'current_location': 'നിലവിലെ സ്ഥാനം',
      'nearby_zones': 'സമീപ പ്രദേശങ്ങൾ',
      'active_alerts': 'സജീവ അലർട്ടുകൾ',
      
      // Profile
      'profile': 'പ്രൊഫൈൽ',
      'edit_profile': 'പ്രൊഫൈൽ തിരുത്തുക',
      'name': 'പേര്',
      'email': 'ഇമെയിൽ',
      'phone': 'ഫോൺ',
      'country': 'രാജ്യം',
      'emergency_contacts': 'അടിയന്തര ബന്ധങ്ങൾ',
      'member_since': 'അംഗമായതുമുതൽ',
      
      // Explore
      'explore': 'അന്വേഷിക്കുക',
      'nearby_places': 'സമീപ സ്ഥലങ്ങൾ',
      'categories': 'വിഭാഗങ്ങൾ',
      'all': 'എല്ലാം',
      'famous': 'പ്രശസ്തം',
      'food': 'ഭക്ഷണം',
      'adventure': 'സാഹസം',
      'hidden_gems': 'മറഞ്ഞ രത്നങ്ങൾ',
      
      // Emergency
      'emergency': 'അടിയന്തരാവസ്ഥ',
      'sos': 'എസ്‌ഒഎസ്',
      'press_and_hold': 'അമർത്തി പിടിക്കുക',
      'police': 'പോലീസ്',
      'ambulance': 'ആംബുലൻസ്',
      'fire': 'ഫയർ വകുപ്പ്',
      'share_location': 'എന്റെ സ്ഥാനം പങ്കിടുക',
      'call_police': 'പോലീസിനെ വിളിക്കുക',
      'report_incident': 'സംഭവം റിപ്പോർട്ട് ചെയ്യുക',
      
      // Incident Report
      'incident_report': 'സംഭവ റിപ്പോർട്ട്',
      'incident_title': 'സംഭവത്തിന്റെ ശീർഷകം',
      'category': 'വിഭാഗം',
      'urgency_level': 'അടിയന്തര നില',
      'description': 'വിവരണം',
      'location': 'സ്ഥലം',
      'submit_report': 'റിപ്പോർട്ട് സമർപ്പിക്കുക',
      'incident_reported': 'സംഭവം റിപ്പോർട്ട് ചെയ്തു',
      'low': 'താഴ്ന്നത്',
      'medium': 'മിതമായത്',
      'high': 'ഉയർന്നത്',
      'critical': 'ഗുരുതരമായത്',
      
      // Settings
      'settings': 'ക്രമീകരണങ്ങൾ',
      'language': 'ഭാഷ',
      'notifications': 'അറിയിപ്പുകൾ',
      'enable_notifications': 'അറിയിപ്പുകൾ പ്രവർത്തനക്ഷമമാക്കുക',
      'dark_mode': 'ഡാർക്ക് മോഡ്',
      'location_tracking': 'ലൊക്കേഷൻ ട്രാക്കിംഗ്',
      'enable_location_tracking': 'ലൊക്കേഷൻ ട്രാക്കിംഗ് പ്രവർത്തനക്ഷമമാക്കുക',
      'about': 'കുറിച്ച്',
      'version': 'പതിപ്പ്',
      'logout': 'ലോഗ് ഔട്ട്',
      
      // Common
      'ok': 'ശരി',
      'cancel': 'റദ്ദാക്കുക',
      'save': 'സംരക്ഷിക്കുക',
      'delete': 'ഇല്ലാതാക്കുക',
      'edit': 'തിരുത്തുക',
      'add': 'ചേർക്കുക',
      'close': 'അടയ്ക്കുക',
      'loading': 'ലോഡ് ചെയ്യുന്നു...',
      'error': 'പിശക്',
      'success': 'വിജയം',
      'no_data': 'ഡാറ്റ ലഭ്യമല്ല',
      'place': 'സ്ഥലം',
      'distance': 'ദൂരം',
      'view_details': 'വിശദാംശങ്ങൾ കാണുക',
      'out_of_100': '100ൽ',
      'current_zone': 'നിലവിലെ മേഖല',
      'time': 'സമയം',
      'crowd_density': 'ജനത്തിരക്ക്',
      'weather': 'കാലാവസ്ഥ',
      'detecting_address': 'വിലാസം കണ്ടെത്തുന്നു...',
      'no_active_alerts': 'ഇപ്പോൾ യാതൊരു അലർട്ടും ഇല്ല. സുരക്ഷിതരായി ഇരിക്കുക!',
      'alert': 'അലർട്ട്',
      'info': 'വിവരം',
      'details_unavailable': 'വിശദാംശങ്ങൾ ലഭ്യമല്ല.',
      'weather_data_unavailable': 'പുതിയ കാലാവസ്ഥ ഡാറ്റ ലഭ്യമല്ല.',
      'rain': 'മഴ',
      'safe_status': 'സുരക്ഷിതം',
      'caution_status': 'ജാഗ്രത',
      'danger_status': 'ഭീഷണി',
      'updating': 'അപ്ഡേറ്റ് ചെയ്യുന്നു...',
      'unknown': 'അജ്ഞാതം',
      'calculating': 'കണക്കാക്കുന്നു...',
      'detecting': 'കണ്ടുപിടിക്കുന്നു...',
      'moments_ago': 'ഒരു നിമിഷം മുമ്പ്',
      'just_now': 'ഇപ്പോൾ തന്നെ',
      'minutes_ago_suffix': 'മിനിറ്റ് മുമ്പ്',
      'hours_ago_suffix': 'മണിക്കൂർ മുമ്പ്',
      'days_ago_suffix': 'ദിവസം മുമ്പ്',
      'entered_zone_title': 'മേഖലയിൽ പ്രവേശിച്ചു',
      'entered_zone_message': 'നിങ്ങൾ പ്രവേശിച്ചിരിക്കുന്നു',
      'tourist_zone': 'സഞ്ചാര മേഖല',
      'market_area': 'മാർക്കറ്റ് പ്രദേശം',
      'remote_forest': 'ദൂരെ ഉള്ള വന്യം',
      'local_police_station': 'പ്രാദേശിക പോലീസ് സ്റ്റേഷൻ',
      'sos_alert': 'SOS മുന്നറിയിപ്പ്',
      'sos_dialog_message': 'നിങ്ങൾ അപകടത്തിലാണോ? ഇത് അടിയന്തര സേവനങ്ങളെ അറിയിക്കും.',
      'send_sos': 'SOS അയയ്ക്കുക',
      'sos_sent': 'SOS മുന്നറിയിപ്പ് അയച്ചു!',
      'brief_title_hint': 'സംഭവത്തിന്റെ ചുരുക്ക ശീർഷകം',
      'enter_incident_title': 'ദയവായി സംഭവത്തിന്റെ ശീർഷകം നൽകുക',
      'select_category': 'ദയവായി ഒരു വിഭാഗം തിരഞ്ഞെടുക്കുക',
      'select_urgency': 'ദയവായി അടിയന്തര നില തിരഞ്ഞെടുക്കുക',
      'description_hint': 'സംഭവത്തിന്റെ വിശദമായ വിവരണം നൽകുക',
      'enter_description': 'ദയവായി വിവരണം നൽകുക',
      'description_min': 'വിവരണം കുറഞ്ഞത് 10 അക്ഷരങ്ങൾ ആയിരിക്കണം',
      'update_location': 'സ്ഥലം അപ്‌ഡേറ്റ് ചെയ്യുക',
      'getting_location': 'സ്ഥലം ലഭ്യമാക്കുന്നു...',
      'error_getting_location': 'നിലവിലുള്ള സ്ഥലം ലഭ്യമാക്കുമ്പോൾ പിശക്',
      'incident_id_label': 'സംഭവ ID',
      'incident_report_success': 'നിങ്ങളുടെ സംഭവം റിപ്പോർട്ട് ചെയ്തു, അധികാരികളെ അറിയിച്ചിട്ടുണ്ട്.',
      'report_info': '📢 നിങ്ങളുടെ റിപ്പോർട്ട് ഉടൻ തന്നെ പ്രാദേശിക അധികാരികൾക്ക് അയയ്ക്കുന്നതാണ്. അധിക വിവരങ്ങൾക്ക് അവർ നിങ്ങളെ ബന്ധപ്പെടാം. രേഖക്കായി നിങ്ങളുടെ സംഭവം ID സൂക്ഷിക്കുക.',
      'theft': 'മോഷണം',
      'assault': 'ആക്രമണം',
      'medical_emergency': 'മെഡിക്കൽ അടിയന്തരാവസ്ഥ',
      'accident': 'അപകടം',
      'missing_person': 'അപ്രത്യക്ഷനായ വ്യക്തി',
      'suspicious_activity': 'സംശയാസ്പദ പ്രവർത്തനം',
      'other': 'മറ്റുള്ളവ',
    },
  };

  // Initialize localization
  static Future<void> initialize() async {
    if (!Hive.isBoxOpen(boxName)) {
      await Hive.openBox(boxName);
    }
    _languageNotifier.value = getCurrentLanguage();
  }

  // Get current language
  static String getCurrentLanguage() {
    try {
      final box = Hive.box(boxName);
      return box.get(languageKey, defaultValue: 'en');
    } catch (e) {
      return 'en';
    }
  }

  // Set language
  static Future<void> setLanguage(String languageCode) async {
    try {
      final box = Hive.box(boxName);
      await box.put(languageKey, languageCode);
      _languageNotifier.value = languageCode;
    } catch (e) {
      print('Error setting language: $e');
    }
  }

  // Get translated string
  static String translate(String key) {
    final currentLanguage = _languageNotifier.value;
    return translations[currentLanguage]?[key] ?? translations['en']?[key] ?? key;
  }

  // Get all available languages
  static List<String> getAvailableLanguages() {
    return translations.keys.toList();
  }

  static ValueListenable<String> get languageNotifier => _languageNotifier;

  // Get language name in English
  static String getLanguageName(String code) {
    switch (code) {
      case 'en':
        return 'English';
      case 'hi':
        return 'Hindi (हिंदी)';
      case 'es':
        return 'Spanish (Español)';
      case 'bn':
        return 'Bengali (বাংলা)';
      case 'mr':
        return 'Marathi (मराठी)';
      case 'te':
        return 'Telugu (తెలుగు)';
      case 'ta':
        return 'Tamil (தமிழ்)';
      case 'gu':
        return 'Gujarati (ગુજરાતી)';
      case 'ur':
        return 'Urdu (اردو)';
      case 'kn':
        return 'Kannada (ಕನ್ನಡ)';
      case 'or':
        return 'Odia (ଓଡ଼ିଆ)';
      case 'ml':
        return 'Malayalam (മലയാളം)';
      default:
        return code;
    }
  }

  // Format date based on current language
  static String formatDate(DateTime date) {
    final currentLanguage = getCurrentLanguage();
    switch (currentLanguage) {
      case 'es':
        final formatter = DateFormat('dd/MM/yyyy', 'es_ES');
        return formatter.format(date);
      default:
        return '${date.day.toString().padLeft(2, '0')}/${date.month.toString().padLeft(2, '0')}/${date.year}';
    }
  }

  // Format time based on current language
  static String formatTime(DateTime dateTime) {
    return '${dateTime.hour}:${dateTime.minute.toString().padLeft(2, '0')}';
  }
}

// Simple translation helper
String tr(String key) => LocalizationService.translate(key);
